#!/usr/bin/env bash

#Start by locking the screen
hyprlock --immediate &

# https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open
# https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP & # for XDPH
#dbus-update-activation-environment --systemd --all &                               # for XDPH
#systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &          # for XDPH

# Policy Authentication Agent (Gnome | KDE)
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#/usr/lib/polkit-kde-authentication-agent-1 & # authentication dialogue for GUI apps

# OSD window for common actions like volume and capslock
exec swayosd-server &

#wallpapers :D
swww-daemon &

# notification daemon
swaync &

# automatic mount storage-devices
udiskie &

# exec-once = ~/.config/hypr/scripts/sleep.sh
# exec-once = ~/.local/scripts/theming.sh

waybar &

# battery notification
#~/.config/hypr/scripts/batterynotify.sh &

# gBar bar 0 &
# gBar bar 1 &

#eww daemon

#blueman-applet &
nm-applet --indicator &

# cursor & touchpad gestures
hyprctl setcursor Bibata-Modern-Classic 16 &
#libinput-gestures-setup start &

# clipboard
wl-paste --type text --watch cliphist store &  # store text data
wl-paste --type image --watch cliphist store & # store image data

# idle
swayidle -w timeout 600 "pidof hyprlock || hyprlock" before-sleep "pidof hyprlock || hyprlock" & # lock screen after 10 min of idle
swayidle -w timeout 1200 "systemctl suspend" &             # hibernate after 20 mins of idle
